spring:
  profiles:
    active: local
  messages:
    basename: messages,errors
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password:
    driver-class-name: org.h2.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 6
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect





  #        dialect: org.hibernate.Oracle10gDialect

  #  data:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page-size: 2000
#

  mail:
    host: smtp.gmail.com
    port: 587
    username: joswxx@gmail.com
    password: osikztmwyrpzppwm
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080


logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
    org.apache.coyote.http11: debug

file:
  dir: /Users/jay/Downloads/ProjectStore

#uploadPath: file:///저장할 로컬 경로/
